# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='category',
            field=models.CharField(default='criminal', max_length=200),
        ),
    ]
